twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        gcategories: '@App\Globals\Categories'
        glicences : '@App\Globals\Licences'

when@test:
    twig:
        strict_variables: true
